site_name: Pipet Docs
dev_addr: 127.0.0.1:5000
copyright: "Pipet is licensed under the <a href=''>MIT license</a>"
repo_url: "https://github.com/pypipet/docs.git"
site_url: https://pypipet.github.io/docs/
theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo
    accent: green
  hljs_languages: 
  - python
extra:
    version: 0.0.1a
    generator: false
markdown_extensions:
  - toc:
      permalink: True
      baselevel: 2
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Introduction: index.md
  - Contributions Guide: about.md
  - Quick Start: 
    - start a project: quick_start/sub.md